jms/assets/urls.py
#!/usr/bin/env python
# coding: utf-8
# Created by guang on
#

from django.conf.urls import url

from . import views


app_name = 'assets'
urlpatterns = [
    url(r'^$', views.AssetListView.as_view(), name='list'),
    url(r'^add/$', views.AssetCreateView.as_view(), name='add'),
    url(r'^(?P<pk>[0-9]+)/del/$', views.AssetDeleteView.as_view(), name='del'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.AssetUpdateView.as_view(), name='update'),
]

jms/jms/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test


@login_required
@user_passes_test(lambda user: user.is_superuser)
def index(request):
    return render(request, 'index.html')

urlpatterns = [
    url('^$', index),
    url(r'^users/', include('users.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^perms/', include('perms.urls')),
    url(r'^admin/', admin.site.urls),
]

jms/assets/models.py
# coding: utf-8

from django.db import models


class Asset(models.Model):
    OS_CHOICE = [
        ('C', 'CentOS'),
        ('U', 'Ubuntu'),
        ('D', 'Debian'),
        ('R', 'Redhat'),
        ('B', 'BSD'),
    ]
    hostname = models.CharField(verbose_name="Hostname", unique=True, max_length=128)
    ip = models.GenericIPAddressField(verbose_name='IP', unique=True)
    port = models.IntegerField(default=22, verbose_name='端口')
    username = models.CharField(max_length=20, verbose_name='管理用户名')
    password = models.CharField(max_length=32, verbose_name='管理密码')
    os = models.CharField(choices=OS_CHOICE, max_length=2, verbose_name='系统平台', default="C")
    is_active = models.BooleanField(default=True, verbose_name='激活')

    def __str__(self):
        return self.hostname

jms/assets/forms.py
from django.forms import ModelForm
from django.forms import TextInput, PasswordInput
from .models import Asset


class AssetForm(ModelForm):
    class Meta:
        model = Asset
        fields = '__all__'
        widgets = {
            'hostname': TextInput(attrs={'placeholder': 'Hostname'}),
            'ip': TextInput(attrs={'placeholder': 'IP'}),
            'port': TextInput(attrs={'placeholder': 'Port'}),
            'username': TextInput(attrs={'placeholder': 'Username'}),
            'password': PasswordInput(attrs={'placeholder': 'Password'}),
        }

jms/assets/views.py
# coding: utf-8

from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, DetailView, View, UpdateView
from django.urls import reverse_lazy

from .forms import AssetForm
from .models import Asset
from users.mixins import LoginRequiredMixin


class AssetListView(LoginRequiredMixin, ListView):
    model = Asset
    context_object_name = 'assets'
    template_name = "assets/list.html"


class AssetCreateView(LoginRequiredMixin, CreateView):
    model = Asset
    form_class = AssetForm
    template_name = "assets/add.html"
    success_url = reverse_lazy("assets:list")


class AssetDetailView(LoginRequiredMixin, DetailView):
    model = Asset
    template_name = "assets/detail.html"


class AssetUpdateView(LoginRequiredMixin, UpdateView):
    model = Asset
    form_class = AssetForm
    template_name = "assets/update.html"
    success_url = reverse_lazy("assets:list")


class AssetDeleteView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        asset_id = self.kwargs.get("pk", 0)
        asset = get_object_or_404(Asset, id=asset_id)
        asset.delete()
        return HttpResponse('删除成功')

jms/assets/templates/assets/add.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
    color: red;
    }
{% endblock %}
{% block content %}
    <h1 class="ui header">资产添加</h1>
    {% if form.errors %}
    <div class="ignored error ui message">
        {{ form.errors }}
    </div>
    {% endif %}
    <form class="ui form" method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <button class="ui button" type="submit">Submit</button>
    </form>
{% endblock %}

jms/assets/templates/assets/detail.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
        color: red;
    }
{% endblock %}
{% block content %}
    <h1 class="ui header">资产详情</h1>
    {% if form.errors %}
    <div class="ignored error ui message">
        {{ form.errors }}
    </div>
    {% endif %}
    <form class="ui form" method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <button class="ui button" type="submit">Submit</button>
    </form>
{% endblock %}

jms/assets/templates/assets/list.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
        color: red;
    }
{% endblock %}
{% block content %}
    <a class="ui right floated small teal labeled button" id="asset_add_btn" href="{% url 'assets:add' %}">添加资产 </a>
    <h1 class="ui header">资产列表</h1>
    <table class="ui striped table">
        <thead>
        <tr>
            <th>主机名</th>
            <th>IP</th>
            <th>端口</th>
            <th>管理账号</th>
            <th>系统</th>
            <th>Active</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for asset in assets %}
            <tr {% if not asset.is_active %} class="error" {% endif %}>
                <td>{{ asset.hostname }}</td>
                <td>{{ asset.ip }}</td>
                <td>{{ asset.port }}</td>
                <td>{{ asset.username }}</td>
                <td>{{ asset.get_os_display }}</td>
                {% if not user.is_active %}
                    <td class="error"><i class="attention icon"></i> 否</td>
                {% else %}
                    <td class="aligned">
                        <i class="green checkmark icon"></i>
                    </td>
                {% endif %}
                <td>
                   <i class="remove asset icon" href="{% url 'assets:del' asset.id %}" value="{{ asset.id }}"></i>
                   <a href="{% url 'assets:update' asset.id %}" ><i class="edit icon"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="ui small modal transition hidden">
        <i class="close icon"></i>
        <div class="header">
            添加资产
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            var csrftoken = Cookies.get('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $('.remove.asset').click(function(){
                var url = $(this).attr('href');
                var id = $(this).attr('value');
                if (confirm('确定删除')){
                    $.post(
                            url,
                            {'id': id},
                            function(){
                                console.log('删除资产成功');
                                location.reload()
                            }

                    )

                }
            })
        })
    </script>
{% endblock %}

jms/assets/templates/assets/update.html
{% extends 'base.html' %}
{% block title %}资产更新{% endblock %}
{% block css %}
    .icon:hover{
        color: red;
    }
{% endblock %}
{% block content %}
    <h1 class="ui header">资产详情</h1>
    {% if form.errors %}
    <div class="ignored error ui message">
        {{ form.errors }}
    </div>
    {% endif %}
    <form class="ui form" method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <button class="ui button" type="submit">Submit</button>
    </form>
{% endblock %}